name: Build Baak HR (Desktop)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        target: [windows, linux, macos]
        include:
          - target: windows
            os: windows-latest
            build_cmd: flutter build windows --release
            artifact_path: build/windows/x64/runner/Release/
          - target: linux
            os: ubuntu-latest
            # FIX: On s'assure d'être en release
            build_cmd: flutter build linux --release 
            artifact_path: build/linux/x64/release/bundle/
          - target: macos
            os: macos-latest
            # FIX: Ajout de --release pour que --no-codesign soit reconnu
            build_cmd: flutter build macos --release --no-codesign
            artifact_path: build/macos/Build/Products/Release/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Linux Dependencies
        if: matrix.target == 'linux'
        run: |
          sudo apt-get update
          # FIX: Ajout de libsecret-1-dev nécessaire pour flutter_secure_storage
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev libsecret-1-dev

      - name: Create .env file
        run: |
          echo "API_URL=${{ secrets.API_URL }}" > .env
        shell: bash

      - name: Get dependencies
        run: flutter pub get

      - name: Build Application
        run: ${{ matrix.build_cmd }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BaakHR-${{ matrix.target }}
          path: ${{ matrix.artifact_path }}